### ISSUE TITLE
What will people get by contributing?

### ISSUE THREAD

**Issue by dipan29** [aceking007/100ProjectsOfCode#7]
Is it some sort of Unpaid Internship on Weed?

**Comment by singhayushh** [comment]
100 Projects is really too much of a time waste. I don't understand why some have even started with this thing.
This might end up hurting their careers real bad.

**Comment by arpit-omprakash** [comment]
@dipan29 LOL probably 😆   
On a serious note, I don't think I want anyone to contribute just because they want to get something out of it. If you want to improve/update the list you are welcome to. But I don't think I can pay you/compensate you for that, so, I won't be requesting anyone or rather forcing anyone to contribute to this.  
If by contribute you mean to build the projects, then I think that will help you build your skills and knowledge, which is much more than anything else that I can offer to you.

**Comment by arpit-omprakash** [comment]
@singhayushh   
The list is a collection of challenging projects that I would want to build someday. **No one is forcing you/anyone else to build anything from it**. If you think it is a time waste, you can just ignore this and forget about it like the hundreds and thousands of forgotten or low lying public repos on GitHub.  
Having said that, I know, I for one would find it really difficult to complete this list in a short period of time. But, not everything is made to be completed, I have knowingly made this list too big to complete (for me and most people). If you/me/anyone else would complete even a few items (even 5-10), they should consider themselves to have considerably improved upon their initial learning base and they should definitely celebrate that.  

But the good thing is, there is no time constraint, *if you are free, don't have anything else to do, or you build the projects in your leisure time, then I think you can still find the time (if not the motivation) to complete the list in a few years without affecting your career*.  
It's **more of how you manage your time** and **if you think this would really help you**. It's the same with any project or list of projects that you build or want to build in the future. If you think it's not worth your time, or if you think you can't manage your time and it will affect other parts of your life, e.g., career, then I think you shouldn't do it. But if you can manage your time and gain something from it, then surely go ahead.

**Comment by arpit-omprakash** [comment]
@dipan29 @singhayushh should I close this if there's nothing else you would like to add?
